### ISSUE TITLE
Console Error

### ISSUE THREAD

**Issue by Gr8z** [RemeJuan/redux-forms-markdown-editor#10]
I get this warning in my console whenever my editor renders.

> Warning: Function components cannot be given refs. Attempts to access this ref will fail. Did you mean to use React.forwardRef()?

Not sure if it's blocking any functionality.

**Comment by RemeJuan** [comment]
If its working then nothings broken, but one of the newer feature realeses of react 16 changed the way refs should be passed down to child components.

Its unlikely that I myself will fix this as I no longer use Redux forms for performance reasons. I am 90% it's actually just a prop change, I know more or less how it needs to be updated to resolve this issue but I'm not sure if that would create any backwards compatability issues with older react versions.

**Comment by Gr8z** [comment]
Yes, it's working fine regardless of the warning. Also, I am using this module with react-final-form, which is just like redux-form but without the redux part.

And reading the docs, the change will most likely break the apps using an older react version.
