### ISSUE TITLE
We need more real use-cases for this

### ISSUE THREAD

**Issue by alyssa1995** [RemeJuan/redux-forms-markdown-editor#9]
The examples given don't provide much info on how to use the editor. Can you be more specific on examples of the different kinds of props we can use? Thanks!

**Comment by RemeJuan** [comment]
Honestly not sure how to be more specific, it's a very short list of props and the only one needing specific config is the `buttonConfig` the rest are standard props that would be applicable to most if not all form input fields.

Is there something specific not making sense?

**Comment by alyssa1995** [comment]
Is there a specific way to change the colors of the `bold`, `italic`, etc. icons? i tried to simply use 'color' as a prop but it doesn't seem to be changing them. i see that they are svgs, so i'm not sure how to go about changing them

**Comment by RemeJuan** [comment]
That would then be the `buttonStyles` prop which is a standard styles object, as they are svg's you should be using `fill` not `color` so something like 
```
buttonStyles={{fill: 'red'}}
```

**Comment by alyssa1995** [comment]
thank you so much! this is an AWESOME component to have, keep up the good work!
